apiVersion: v1
kind: Service
metadata:
  labels:
    service: emakin-tcp
  name: emakin-tcp
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
    - name: "443"
      port: 443
      targetPort: 443
    - name: "7180"
      port: 7180
      targetPort: 7180
    - name: "25"
      port: 25
      targetPort: 25
    - name: "587"
      port: 587
      targetPort: 587
    - name: "465"
      port: 465
      targetPort: 465
  selector:
    service: emakin
  type: LoadBalancer
