apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: emakin
  name: emakin
spec:
  replicas: 1
  selector:
    matchLabels:
      service: emakin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: emakin
    spec:
      containers:
        - env:
            - name: AK_AntivirusServerUrl
              value: tcp://clamav:3310
            - name: AK_BasexConnStr
              value: http://admin:admin@basex:1984/
            - name: AK_DbConnStr
              value: Host=postgre;Database={{ .Values.db_name }};Username={{ .Values.db_user }};Password={{ .Values.db_password }};
            - name: AK_DbProvider
              value: PostgreSql
            - name: AK_RedisConnStr
              value: redis,allowAdmin=true
            - name: AK_TikaConnStr
              value: http://tika:9998/
            - name: AK_WopiConnStr
              value: http://onlyoffice/hosting/discovery
            - name: AK_DEFAULT_ADMIN
              value: {{ .Values.emk_admin }}
            - name: AK_DEFAULT_ADMIN_PASSWORD
              value: {{ .Values.emk_password }}
          image: 6kare/emakin:8.5
          name: emakin
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP
            - containerPort: 7180
              protocol: TCP
            - containerPort: 25
              protocol: TCP
            - containerPort: 587
              protocol: TCP
            - containerPort: 465
              protocol: TCP
          volumeMounts:
            - mountPath: /app/Configuration/Data
              name: emkdata
      restartPolicy: Always
      securityContext:
          sysctls:
              - name: net.ipv4.ip_unprivileged_port_start
                value: '0'
      volumes:
        - name: emkdata
          persistentVolumeClaim:
            claimName: emkdata
