apiVersion: v1
kind: Service
metadata:
  labels:
    service: onlyoffice
  name: onlyoffice
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
    - name: "443"
      port: 443
      targetPort: 443
  selector:
    service: onlyoffice
